# Generated by Django 4.2.18 on 2025-01-19 16:49

from django.db import migrations, models
import django.db.models.deletion
import produtores.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em?')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em?')),
                ('active_bit', models.BooleanField(default=True, verbose_name='Bit ativo?')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da fazenda')),
                ('cidade', models.CharField(max_length=128, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='Sigla do Estado (2 caractéres | Ex. SP, RJ)', max_length=2, verbose_name='Estado')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Área total em hectares', max_digits=10, null=True, verbose_name='Área total')),
                ('area_agricultavel', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Área agricultável em hectares', max_digits=10, null=True, verbose_name='Área agricultável')),
                ('area_vegetacao', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Área de vegetação em hectares', max_digits=10, null=True, verbose_name='Área de vegetação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em?')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em?')),
                ('active_bit', models.BooleanField(default=True, verbose_name='Bit ativo?')),
                ('nome', models.CharField(help_text='Nome completo', max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, help_text='Apenas números sem pontos ou traços', max_length=11, null=True, unique=True, validators=[produtores.validators.validate_cpf], verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, help_text='Apenas números sem pontos ou traços', max_length=14, null=True, unique=True, validators=[produtores.validators.validate_cnpj], verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtores',
            },
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em?')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em?')),
                ('active_bit', models.BooleanField(default=True, verbose_name='Bit ativo?')),
                ('nome', models.CharField(default='Safra', max_length=128, verbose_name='Safra')),
                ('ano', models.IntegerField(help_text='Ano da safra', verbose_name='Ano')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safras', to='produtores.fazenda', verbose_name='Fazenda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fazenda',
            name='produtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fazendas', to='produtores.produtor', verbose_name='Produtor'),
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em?')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em?')),
                ('active_bit', models.BooleanField(default=True, verbose_name='Bit ativo?')),
                ('nome', models.CharField(help_text='Nome da cultura plantada', max_length=255, verbose_name='Nome cultura')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='produtores.fazenda', verbose_name='Fazenda')),
                ('safra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='culturas', to='produtores.safra', verbose_name='Safra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
